#!/usr/bin/env bash
#
# clean.sh — reclaim disk space by deleting regenerable build artifacts.
#
# Everything this script removes is either git-ignored or re-downloaded /
# re-generated by a normal build (npm install, ng build, cap sync, gradle,
# mvn). Your source code is NEVER touched.
#
# Usage:
#   ./clean.sh              # clean project-local artifacts (safe, default)
#   ./clean.sh --dry-run    # show what WOULD be deleted, delete nothing
#   ./clean.sh --deep       # also clear shared caches (~/.gradle, ~/.npm)
#   ./clean.sh --deep -n    # preview a deep clean
#
# After cleaning, to get running again:
#   Frontend :  cd frontend && npm install
#   Backend  :  cd backend  && npm install
#   Android  :  cd frontend && npm run cap:android      (rebuilds + syncs)
#   iOS      :  cd frontend && npm run cap:ios
#
set -euo pipefail

# Resolve repo root as the directory this script lives in.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DRY_RUN=0
DEEP=0
for arg in "$@"; do
  case "$arg" in
    -n|--dry-run) DRY_RUN=1 ;;
    --deep)       DEEP=1 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "Unknown option: $arg (try --help)"; exit 1 ;;
  esac
done

# --- helpers ---------------------------------------------------------------

human() { du -sh "$1" 2>/dev/null | cut -f1; }

FREED_KB=0
add_freed() {
  local kb
  kb=$(du -sk "$1" 2>/dev/null | cut -f1 || echo 0)
  FREED_KB=$((FREED_KB + kb))
}

# rm_path <path> : delete a file or directory if it exists, reporting size.
rm_path() {
  local target="$1"
  [ -e "$target" ] || return 0
  local size; size=$(human "$target")
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '  would remove  %-8s %s\n' "$size" "${target#$ROOT/}"
  else
    add_freed "$target"
    rm -rf "$target"
    printf '  removed       %-8s %s\n' "$size" "${target#$ROOT/}"
  fi
}

# rm_glob <dir> <name> : find and delete matching dirs/files under <dir>.
rm_glob() {
  local base="$1" pattern="$2" type="${3:-d}"
  [ -d "$base" ] || return 0
  while IFS= read -r -d '' match; do
    rm_path "$match"
  done < <(find "$base" -type "$type" -name "$pattern" -prune -print0 2>/dev/null)
}

section() { echo; echo "== $1 =="; }

# --- what we clean ---------------------------------------------------------

echo "Cleaning: $ROOT"
[ "$DRY_RUN" -eq 1 ] && echo "(dry run — nothing will be deleted)"

section "Node modules (frontend, backend, root, services)"
rm_path "$ROOT/node_modules"
rm_path "$ROOT/frontend/node_modules"
rm_path "$ROOT/backend/node_modules"
# any other node_modules that appear in services
rm_glob "$ROOT/media-service" node_modules
rm_glob "$ROOT/notification-service" node_modules

section "Frontend web build & caches"
rm_path "$ROOT/frontend/dist"
rm_path "$ROOT/frontend/.angular"
rm_path "$ROOT/frontend/.firebase"

section "Android generated package (build outputs + synced assets)"
rm_path "$ROOT/frontend/android/build"
rm_path "$ROOT/frontend/android/app/build"
rm_path "$ROOT/frontend/android/.gradle"
rm_path "$ROOT/frontend/android/capacitor-cordova-android-plugins"
rm_path "$ROOT/frontend/android/app/src/main/assets/public"
rm_path "$ROOT/frontend/android/app/src/main/assets/capacitor.config.json"
rm_path "$ROOT/frontend/android/app/src/main/assets/capacitor.plugins.json"
rm_path "$ROOT/frontend/android/app/src/main/res/xml/config.xml"

section "iOS generated package (build outputs + synced assets)"
rm_path "$ROOT/frontend/ios/App/App/public"
rm_path "$ROOT/frontend/ios/App/build"
rm_path "$ROOT/frontend/ios/App/Pods"
rm_path "$ROOT/frontend/ios/DerivedData"
rm_path "$ROOT/frontend/ios/capacitor-cordova-ios-plugins"

section "Java service builds (Maven target)"
rm_glob "$ROOT/media-service" target
rm_glob "$ROOT/notification-service" target

section "Logs & misc"
rm_glob "$ROOT/backend/logs" '*.log' f
rm_glob "$ROOT" 'npm-debug.log*' f
rm_glob "$ROOT" '*.tmp' f
rm_path "$ROOT/.DS_Store"

if [ "$DEEP" -eq 1 ]; then
  section "DEEP: shared caches (slow to rebuild — re-downloaded on next build)"
  rm_path "$HOME/.gradle/caches"
  rm_path "$HOME/.gradle/daemon"
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "  would run     npm cache clean --force"
  else
    npm cache clean --force >/dev/null 2>&1 && echo "  cleaned       npm cache (~/.npm)" || true
  fi
fi

# --- summary ---------------------------------------------------------------

echo
if [ "$DRY_RUN" -eq 1 ]; then
  echo "Dry run complete. Re-run without --dry-run to delete."
else
  FREED_MB=$((FREED_KB / 1024))
  echo "Done. Reclaimed ~${FREED_MB} MB."
fi
