name: Deploy Notification Service

on:
  push:
    branches: [main]
    paths:
      - 'notification-service/**'
      - '.github/workflows/deploy-notification.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    secrets: inherit
    with:
      service_name: notification-service
      context_path: ./notification-service
      image_suffix: shiv-agri-notification
