name: Deploy Nginx

on:
  push:
    branches: [main]
    paths:
      - 'nginx/**'
      - '.github/workflows/deploy-nginx.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    secrets: inherit
    with:
      service_name: nginx
      context_path: ./nginx
      image_suffix: shiv-agri-nginx
      use_build_cache: false
